version: "3.5"
 
services:
  service-event:
    image: rabbitmq:3.8.13-management
    container_name: component-event
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=aforo255
      - RABBITMQ_DEFAULT_PASS=aforo255
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - aforo255  
  service-discovery:
    image: consul:1.9.10
    container_name: component-discovery
    restart: always
    ports:
    - 8500:8500
    networks:
    - aforo255
  service-balancer:
    image: fabiolb/fabio:1.5.15-go1.15.5
    container_name: component-balancer
    restart: always
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=component-discovery:8500
    ports:
    - 9998:9998
    - 9999:9999
    networks:
    - aforo255
    depends_on:
    - service-discovery
  service-config:
    image: nacos/nacos-server:v2.0.3
    container_name: component-config 
    restart: always
    environment:
    - MODE=standalone
    ports:
    - 8848:8848
    networks:
    - aforo255
  service-tracer:
    image: openzipkin/zipkin:2
    container_name: component-tracer 
    restart: always
    ports:
    - 9411:9411
    networks:
    - aforo255
  service-metrics:
    image: prom/prometheus:v2.31.1
    container_name: component-metrics
    restart: always
    ports:
    - 9090:9090
    volumes:
    - C:/docker/net7/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
    - aforo255
  service-analytics:
    image: grafana/grafana:8.2.3
    container_name: component-analytics
    restart: always
    ports:
    - 3000:3000
    networks:
    - aforo255
    depends_on:
    - service-metrics	
  service-log-elastic:    
    image: elasticsearch:6.8.20
    container_name: component-log-elastic
    restart: always
    ports:
    - 9200:9200
    environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    networks:
    - aforo255
  service-log-kibana:
    image: kibana:6.8.20
    container_name: component-log-kibana
    restart: always
    ports:
    - 5601:5601
    depends_on:
    - service-log-elastic
    environment:
    - ELASTICSEARCH_URL=http://component-log-elastic:9200
    networks:
    - aforo255	
 
networks:
  aforo255:
    name: micro